# Generated by Django 2.0.4 on 2018-04-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wire_profile', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followerId',
            new_name='follower_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followingId',
            new_name='following_id',
        ),
    ]
